## Thursday {{date}}

Quick test... confirm that updating a dataset results in submission.  It does.

So...

donkey is working as expected.  It can poll rucio to discover new datasets matching a given pattern.  (The pattern match on the dataset name is by the rucio rules... it may be better to do a broad capture of dataset names and then apply a regex locally... but I suspect that will introduce inefficiencies / slam the rucio server as the datasets become large...)


Well... donkey picks it up...  b/c I have echo in the actor script, not actually submitting.

Modified the actor... now it should submit, but I don't see the actor being run?
... because I have a prescale set.  So it won't pick it up for a few more attempts.  Duh.  So, this time for sure...

Good.  Jobs got submittied this time.  (Bad, they died... but b/c ... well, not at all clear why monitor thinks that there are failed tasks... looks like it is running when I dig into things.)

Polling at 5min interval... I run into a `sh.ErrorReturnCode_10` exception on rucio... 
`
2022-09-15 10:53:32,672	ERROR	Database exception.
Details: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "sprucio02.sdcc.bnl.gov" (10.42.34.176) and accepting
	TCP/IP connections on port 5432?
`
Looks like a transient error, b/c I was able to do a rucio ls shortly after.